apiVersion: certmanager.io/v1alpha2
kind: Certificate
metadata:
  name: arendse.xyz
  namespace: default
spec:
  secretName: arendse.xyz.tls
  duration: 2190h   #   90d
  renewbefore: 360h #   15d
  commonName: arendse.xyz
  dnsNames:
  - www.arendse.xyz
  issuerRef:
    name: ca-issuer
    kind: Issuer

