apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cardigann
  name: cardigann
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cardigann
    spec:
      containers:
      - env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: TZ
          value: '"Africa/Johannaesburg"'
        image: linuxserver/cardigann
        name: cardigann
        ports:
        - containerPort: 5060
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: cardigann-claim0
      restartPolicy: Always
      volumes:
      - name: cardigann-claim0
        persistentVolumeClaim:
          claimName: cardigann-claim0
status: {}
