---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbhydra
  namespace: nzbhydra
  labels:
    app: nzbhydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbhydra
  template:
    metadata:
      labels:
        app: nzbhydra
    spec:
      containers:
        - name: nzbhydar
          image: linuxserver/nzbhydra2
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "117"
            - name: PUID
              value: "113"
          ports:
            - containerPort: 5076
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          hostPath:
            type: Directory
            path: /home/docker/nzbhydra2/config


