apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: htpcmanager
  name: htpcmanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: htpcmanager
    spec:
      containers:
      - env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: TZ
          value: Etc/UTC
        image: linuxserver/htpcmanager
        name: htpcmanager
        ports:
        - containerPort: 8085
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: htpcmanager-claim0
      restartPolicy: Always
      volumes:
      - name: htpcmanager-claim0
        persistentVolumeClaim:
          claimName: htpcmanager-claim0
status: {}
