---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - 6f3806410f7b.sn.mynetname.net
      secretName: sonarr-secret
  rules:
    - host: 6f3806410f7b.sn.mynetname.net
      http:
        paths:
          - path: /sonarr
            backend:
              serviceName: sonarr
              servicePort: 8989
