apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole
  namespace: pihole
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - www.arendse.xyz
    - pihole.arendse.xyz
    secretName: pihole-secret
  rules:
  - host: www.arendse.xyz
    http:
      paths:
      - path: /pihole
        backend:
          serviceName: pihole
          servicePort: 80
  - host: pihole.arendse.xyz
    http:
      paths:
      - backend:
          serviceName: pihole
          servicePort: 80
