---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole 
spec:
  selector:
    app: pihole
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: dns
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: client-udp
    protocol: UDP
    port: 67
    targetPort: 67
