---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: jackett
  labels:
    app: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett
        env:
        - name: PGID
          value: "117"
        - name: PUID
          value: "113"
        - name: TZ
          value: '"Africa/Johannaesburg"'
        ports:
        - containerPort: 9117
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: downloads
      volumes:
      - name: config
        hostPath:
          path: /home/docker/jackett/config
      - name: downloads
        hostPath:
          path: /home/docker/jackett/downloads
