apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: tautulli
  name: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tautulli
    spec:
      containers:
      - env:
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: TZ
          value: '"Africa/Johannaesburg"'
        image: linuxserver/tautulli
        name: tautulli
        ports:
        - containerPort: 8181
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: tautulli-claim0
        - mountPath: /logs
          name: tautulli-claim1
        - mountPath: /etc/localtime
          name: tautulli-claim2
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: tautulli-claim0
        persistentVolumeClaim:
          claimName: tautulli-claim0
      - name: tautulli-claim1
        persistentVolumeClaim:
          claimName: tautulli-claim1
      - name: tautulli-claim2
        persistentVolumeClaim:
          claimName: tautulli-claim2
          readOnly: true
status: {}
