apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: media
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: greg.arendse@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # ACME DNS-01 provider configurations
    solvers:
    - dns01:
        cloudflare:
          email: greg.arendse@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key.txt

