apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: portainer
    spec:
      containers:
      - args:
        - -H
        - unix:///var/run/docker.sock
        image: portainer/portainer
        name: portainer
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: portainer-claim0
        - mountPath: /data
          name: portainer-claim1
      restartPolicy: Always
      volumes:
      - name: portainer-claim0
        persistentVolumeClaim:
          claimName: portainer-claim0
      - name: portainer-claim1
        persistentVolumeClaim:
          claimName: portainer-claim1
status: {}
